### ISSUE TITLE
Legends are ignored

### ISSUE THREAD

**Issue by damnitrahul** [brammitch/recharts-to-png#1]
I am trying to implement this package to download images of my charts but chart legends are being ignored while downloading Images. How to include legends in the downloaded images?

Chart: 
![image](https://user-images.githubusercontent.com/31034782/93080872-fea09a00-f6ab-11ea-8ca2-761cda984635.png)

Downloaded Image: 
![test (4)](https://user-images.githubusercontent.com/31034782/93080893-06603e80-f6ac-11ea-8723-da81a420e07f.png)

**Comment by brammitch** [comment]
The problem is that the legend is in a separate `div` from the main SVG element, and it is a mix of SVGs and regular HTML elements.

I think switching to [html2canvas](https://github.com/niklasvh/html2canvas) will solve the issue. This will make recharts-to-png not much more than a simple wrapper around html2canvas, but it should get the job done.
