### ISSUE TITLE
How to use Recharts-to-png in class component react

### ISSUE THREAD

**Issue by karthikn1050** [brammitch/recharts-to-png#445]
I am developed the project fully in class component. i want to create option to download the chart that i created with recharts but in the recharts documentation the example is only available for functional. i really need this for my class component kindly guide me how to use it on class component

**Comment by brammitch** [comment]
The documentation is only for functional components because this library exports a hook, which will not work with class components.

Here's an example of how you could implement the download capability on your own with a class component:
https://codesandbox.io/s/recharts-download-class-component-sktfx9?file=/src/App.tsx

**Comment by brammitch** [comment]
I'll work on getting a component added to this library that will let you use Render Props in a class component, instead of the hook.
